# fly.toml app configuration file generated for wax-shelves on 2023-09-27T16:36:29-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wax-shelves"
primary_region = "den"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="myapp_data"
  destination="/data"
